version: '3.1'

services:
  boostcamp-blog-development:
    platform: linux/x86_64
    container_name: boostcamp-blog-development
    image: 'mysql:8.0'
    ports:
      - '3310:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'development'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
